package cn.greatoo.easymill.ui.teach.griperA;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.CheckBox;

import javafx.scene.layout.GridPane;

public class TeachPickViewController {
	@FXML
	private GridPane generalGridPane;
	@FXML
	private TextField xTextField;
	@FXML
	private Button xResetBt;
	@FXML
	private TextField wTextField;
	@FXML
	private Button wResetBt;
	@FXML
	private TextField yTextField;
	@FXML
	private Button yResetBt;
	@FXML
	private TextField pTextField;
	@FXML
	private Button pResetBt;
	@FXML
	private TextField zTextField;
	@FXML
	private Button zResetBt;
	@FXML
	private TextField rTextField;
	@FXML
	private Button rResetBt;
	@FXML
	private CheckBox checkBox;
	@FXML
	private Button changeBt;

	public void init() {
		// TODO Auto-generated method stub
		
	}
	@FXML
	public void xResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#wResetBt].onAction
	@FXML
	public void wResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#yResetBt].onAction
	@FXML
	public void yResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#pResetBt].onAction
	@FXML
	public void pResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#zResetBt].onAction
	@FXML
	public void zResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#rResetBt].onAction
	@FXML
	public void rResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#checkBox].onAction
	@FXML
	public void checkBoxAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#changeBt].onAction
	@FXML
	public void changeBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
