CREATE TABLE ADMIN.WORKAREA_BOUNDARIES (
	WORKAREA_ID INTEGER NOT NULL,
	BOTTOMCOORD INTEGER NOT NULL,
	TOPCOORD INTEGER NOT NULL,
	CONSTRAINT PK_BOUND_ID PRIMARY KEY (WORKAREA_ID),
	CONSTRAINT FK_BOTTOMCOORD_BOUND FOREIGN KEY (BOTTOMCOORD) REFERENCES ADMIN.COORDINATES(ID) ON DELETE CASCADE,
	CONSTRAINT FK_TOPCOORD_BOUND FOREIGN KEY (TOPCOORD) REFERENCES ADMIN.COORDINATES(ID) ON DELETE CASCADE,
	CONSTRAINT FK_WA_ID FOREIGN KEY (WORKAREA_ID) REFERENCES ADMIN.WORKAREA(ID) ON DELETE CASCADE
) ;
