package cn.greatoo.easymill.ui.set;

import java.sql.SQLException;

import cn.greatoo.easymill.db.util.DBHandler;
import cn.greatoo.easymill.process.ProcessFlow;
import cn.greatoo.easymill.util.FullTextField;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import cn.greatoo.easymill.ui.general.AbstractFormView;
public class SaveViewController {
	@FXML
	private GridPane saveGridPane;
	@FXML
	private Button saveBt;
	@FXML
	private FullTextField fulltxtName;
	private ProcessFlow processFlow;

	public void init() {		
		fulltxtName.setOnChange(new ChangeListener<String>() {
			@Override
			public void changed(final ObservableValue<? extends String> arg0, final String oldValue, final String newValue) {
				//getPresenter().nameChanged(newValue);
			}
		});
	}
	// Event Listener on Button[#saveBt].onMouseClicked
	@FXML
	public void save(MouseEvent event) throws SQLException {
		// TODO Autogenerated
		try{			
			DBHandler.getInstance().SaveProcessFlow(processFlow);
		}
		catch (SQLException e) {
			e.printStackTrace();
		}
	}		
	// Event Listener on FullTextField[#fulltxtName].onMouseClicked
	@FXML
	public void nameChanged(MouseEvent event) {
		processFlow.setName(fulltxtName.getText());;
	}
	
	
}
