package cn.greatoo.easymill.ui.set.table.load;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.GridPane;

public class PickViewController {
	@FXML
	private GridPane gridPane;
	@FXML
	private TextField XField;
	@FXML
	private TextField YField;
	@FXML
	private TextField ZField;
	@FXML
	private Button resetBt;

	public void init() {
		// TODO Auto-generated method stub
		
	}
	// Event Listener on TextField[#XField].onAction
	@FXML
	public void XFieldAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#YField].onAction
	@FXML
	public void YField(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#ZField].onAction
	@FXML
	public void ZField(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#resetBt].onAction
	@FXML
	public void resetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
