package cn.greatoo.easymill.ui.teach;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class TeachMainContentViewController {
	@FXML
	private Button btnStart;
	@FXML
	private Button btnStartAll;
	@FXML
	private Button reset;
	@FXML
	private Button save;

	public void init() {
		
		
	}
	@FXML
	public void btnStartAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnStartAll].onAction
	@FXML
	public void btnStartAllAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#reset].onAction
	@FXML
	public void resetAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#save].onAction
	@FXML
	public void saveAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
