package cn.greatoo.easymill.ui.set.table.load;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.CheckBox;

import javafx.scene.layout.GridPane;

public class DeviceViewController {
	@FXML
	private GridPane gridPane;
	@FXML
	private ComboBox cbbComboBox;
	@FXML
	private Button changeBt;
	@FXML
	private CheckBox singleCycle;
	@FXML
	private ComboBox gridComBox;

	public void init() {
		cbbComboBox.getItems().add("777777");
		cbbComboBox.getItems().add("8888888");
		gridComBox.getItems().add("666666");
		gridComBox.getItems().add("555555");
	}
	// Event Listener on ComboBox[#cbbComboBox].onAction
	@FXML
	public void cbbComboBoxAction(ActionEvent event) {
		cbbComboBox.getItems().add("1111111");
	}
	// Event Listener on Button[#changeBt].onAction
	@FXML
	public void changeBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on CheckBox[#singleCycle].onAction
	@FXML
	public void isSelect(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#gridComBox].onAction
	@FXML
	public void gridComBoxAction(ActionEvent event) {
		
	}
	
}
