package cn.greatoo.easymill.ui.set;

import cn.greatoo.easymill.util.FullTextField;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.layout.HBox;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;

import javafx.scene.layout.GridPane;

public class OpenViewController {
	@FXML
	private GridPane saveGridPane;
	@FXML
	private HBox totalHBox;
	@FXML
	private HBox hbox;
	@FXML
	private Button btnLoad;
	@FXML
	private TableView table;
	@FXML
	private FullTextField fulltxtName;
	
	// Event Listener on Button[#btnLoad].onMouseClicked
	@FXML
	public void load(MouseEvent event) {
		// TODO Autogenerated
	}

	public void init() {
		fulltxtName.setOnChange(new ChangeListener<String>() {
			@Override
			public void changed(final ObservableValue<? extends String> arg0, final String oldValue, final String newValue) {
				//getPresenter().nameChanged(newValue);
			}
		});
		
	}
}
