package cn.greatoo.easymill.ui.set.cnc;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.layout.GridPane;

public class CNCFinishedWPViewController {
	@FXML
	private GridPane generalGridPane;
	@FXML
	private TextField fulltxtL;
	@FXML
	private TextField fulltxtW;
	@FXML
	private TextField fulltxtH;
	@FXML
	private Button hResetBt;
	@FXML
	private TextField fulltxtWT;
	@FXML
	private Button calculateBt;
	@FXML
	private Button resetBt;
	@FXML
	private Button wResetBt;
	@FXML
	private Button LResetBt;

	public void init() {
		
		
	}
	@FXML
	public void hResetBtAction(ActionEvent event) {
		
	}
	
	@FXML
	public void calculateBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#resetBt].onAction
	@FXML
	public void resetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#wResetBt].onAction
	@FXML
	public void wResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#LResetBt].onAction
	@FXML
	public void LResetBtAction(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
