package cn.greatoo.easymill.cnc;

public enum EDeviceGroup {
	STACKING, BASIC_STACK_PLATE, PRE_PROCESSING, CNC_MACHINE, POST_PROCESSING, CONVEYOR, CONVEYOR_EATON, OUTPUT_BIN, UNLOAD_PALLET, PALLET
}
